/*
 Navicat Premium Data Transfer

 Source Server         : 127.0.0.1
 Source Server Type    : MySQL
 Source Server Version : 80025
 Source Host           : localhost:3306
 Source Schema         : migoo

 Target Server Type    : MySQL
 Target Server Version : 80025
 File Encoding         : 65001

 Date: 06/12/2023 23:40:20
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for sys_menu
-- ----------------------------
DROP TABLE IF EXISTS `sys_menu`;
CREATE TABLE `sys_menu` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '菜单ID',
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '菜单名称',
  `permission` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '权限标识',
  `menu_type` tinyint NOT NULL COMMENT '菜单类型',
  `sort` int NOT NULL DEFAULT '0' COMMENT '显示顺序',
  `parent_id` bigint NOT NULL DEFAULT '0' COMMENT '父菜单ID',
  `path` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '路由地址',
  `icon` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '#' COMMENT '菜单图标',
  `component_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '组件名称',
  `component` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '组件路径',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '菜单状态',
  `page_type` tinyint NOT NULL DEFAULT '2' COMMENT '页面类型，1: 会员页面；2:管理员页面',
  `visible` tinyint NOT NULL DEFAULT '1' COMMENT '是否可见',
  `always_show` tinyint NOT NULL DEFAULT '0' COMMENT '总是显示：1:是，0:否',
  `keep_alive` tinyint NOT NULL DEFAULT '1' COMMENT '是否缓存',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4143 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='菜单权限表';

-- ----------------------------
-- Records of sys_menu
-- ----------------------------
BEGIN;
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (1, '工作台', 'dashboard', 2, 0, 0, '/index', 'ep:alarm-clock', 'Dashboard', 'dashboard/index', 1, 2, 1, 1, 1, 0, '', NULL, '超级管理员', '2023-10-26 17:20:34');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2, '系统管理', 'system:manager', 1, 9998, 0, '/system', 'ep:setting', NULL, '', 1, 2, 1, 0, 1, 0, '', '2022-04-29 18:34:52', '超级管理员', '2023-09-27 22:48:18');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (100, '主题测试', 'layout:setting', 3, 0, 1, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2023-07-23 18:56:46', '超级管理员', '2023-07-23 18:56:46');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (200, '用户管理', 'system:user:query', 2, 0, 2, 'user', 'ep:user', 'SystemUser', 'system/user/index', 1, 2, 1, 1, 1, 0, '', '2022-04-29 18:45:02', '超级管理员', '2023-10-26 17:20:41');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (201, '角色管理', 'system:role:query', 2, 1, 2, 'role', 'fa-solid:user-plus', 'UserRole', 'system/role/index', 1, 2, 1, 1, 1, 0, '', '2022-04-29 18:45:02', '超级管理员', '2023-09-27 22:49:31');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (202, '部门管理', 'system:dept:query', 2, 2, 2, 'dept', 'ep:basketball', 'SystemDept', 'system/dept/index', 1, 2, 1, 1, 1, 0, '', '2022-04-29 18:45:02', '超级管理员', '2023-09-27 22:50:05');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (203, '岗位管理', 'system:post:query', 2, 3, 2, 'post', 'ep:postcard', 'SystemPost', 'system/post/index', 1, 2, 1, 1, 1, 0, '', '2022-04-29 18:45:02', '超级管理员', '2023-09-27 22:50:32');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (204, '菜单管理', 'system:menu:query', 2, 4, 2, 'menu', 'ep:menu', 'SystemMenu', 'system/menu/index', 1, 2, 1, 1, 1, 0, '', '2022-04-29 18:45:02', '超级管理员', '2023-09-27 22:50:53');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2000, '新增', 'system:user:add', 3, 0, 200, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 13:55:34', '超级管理员', '2022-05-01 16:27:05');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2001, '修改', 'system:user:update', 3, 1, 200, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 13:55:59', '超级管理员', '2023-09-30 15:51:13');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2002, '删除', 'system:user:remove', 3, 3, 200, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 13:56:20', '超级管理员', '2022-05-01 16:27:12');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2003, '重置密码', 'system:user:reset-password', 3, 4, 200, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 14:00:56', '超级管理员', '2022-05-01 16:27:16');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2004, '分配角色', 'system:permission:assign-user-role', 3, 4, 200, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:05:28', '超级管理员', '2022-05-01 16:27:23');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2010, '新增', 'system:role:add', 3, 0, 201, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:00:30', '超级管理员', '2022-05-01 16:27:37');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2011, '修改', 'system:role:update', 3, 1, 201, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:01:01', '超级管理员', '2023-10-01 10:18:19');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2012, '删除', 'system:role:remove', 3, 2, 201, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:01:24', '超级管理员', '2022-05-01 16:27:53');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2013, '分配菜单', 'system:permission:assign-role-menu', 3, 3, 201, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:06:41', '超级管理员', '2022-05-01 16:27:57');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2020, '新增', 'system:dept:add', 3, 0, 202, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:07:56', '超级管理员', '2022-05-01 16:28:02');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2021, '修改', 'system:dept:update', 3, 1, 202, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:08:12', '超级管理员', '2023-10-01 10:18:13');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2022, '删除', 'system:dept:remove', 3, 3, 202, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:08:24', '超级管理员', '2022-05-01 16:28:10');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2030, '新增', 'system:post:add', 3, 0, 203, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:15:22', '超级管理员', '2022-05-01 16:28:21');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2031, '修改', 'system:post:update', 3, 1, 203, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:18:11', '超级管理员', '2023-10-01 10:17:56');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2032, '删除', 'system:post:remove', 3, 2, 203, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:18:28', '超级管理员', '2022-05-01 16:28:42');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2040, '新增', 'system:menu:add', 3, 0, 204, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:19:11', '超级管理员', '2022-05-01 16:28:48');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2041, '修改', 'system:menu:update', 3, 1, 204, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:19:42', '超级管理员', '2023-10-01 10:18:06');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2042, '删除', 'system:menu:remove', 3, 2, 204, '', '', NULL, '', 1, 2, 1, 0, 1, 0, '超级管理员', '2022-05-01 16:19:56', '超级管理员', '2022-05-01 16:28:57');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4110, '项目管理', '', 1, 99, 0, '/project', 'ep:promotion', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-08 16:59:07', '超级管理员', '2023-12-07 14:54:53');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4111, '项目列表', 'system:project:query', 2, 5, 2, 'project', 'fa:table', 'ProjectList', 'Project/table/index.vue', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-08 17:03:17', '超级管理员', '2023-12-07 15:14:25');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4112, '新增', 'system:project:add', 3, 0, 4111, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-08 17:03:45', '超级管理员', '2023-11-08 17:03:45');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4113, '修改', 'system:project:update', 3, 1, 4111, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-08 17:04:03', '超级管理员', '2023-11-08 17:04:03');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4114, '删除', 'system:project:remove', 3, 2, 4111, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-08 17:04:20', '超级管理员', '2023-11-08 17:04:20');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4115, '项目设置', 'project:info:query', 2, 0, 4110, 'profile', 'ep:promotion', 'ProjectInfo', 'Project/info/index.vue', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-10 14:54:29', '超级管理员', '2023-12-07 15:15:41');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4118, '测试跟踪', '', 1, 1, 0, '/track', 'ep:coffee', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-13 16:04:04', '超级管理员', '2023-11-29 17:51:17');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4119, '测试用例', '', 2, 0, 4118, 'case', 'ep:burger', 'CaseTracked', 'Tracked/case/index.vue', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-13 16:05:53', '超级管理员', '2023-11-30 10:17:47');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4120, '测试评审', '', 2, 1, 4118, 'review', 'ep:ice-cream', 'ReviewTracked', 'Tracked/review/index.vue', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-13 16:08:46', '超级管理员', '2023-11-30 10:18:33');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4121, '测试计划', '', 2, 2, 4118, 'plan', 'ep:hot-water', 'PlanTracked', 'Tracked/plan/index.vue', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-13 16:09:35', '超级管理员', '2023-11-30 10:19:10');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4122, '新增用例', '', 2, 99, 4118, 'case/add', 'ep:document-add', 'CaseAdd', 'Tracked/case/CaseEditor.vue', 1, 2, 0, 0, 1, 0, '超级管理员', '2023-11-14 17:04:14', '超级管理员', '2023-12-05 15:51:21');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4123, '编辑用例', '', 2, 99, 4118, 'case/edit/:id', 'ep:edit', 'CaseEdit', 'Tracked/case/CaseEditor.vue', 1, 2, 0, 0, 1, 0, '超级管理员', '2023-11-14 17:31:39', '超级管理员', '2023-12-05 15:51:28');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4124, '规划&评审', '', 2, 99, 4118, 'review/:reviewId/associated-use-cases', 'ep:link', 'ReviewAssociatedCase', 'Tracked/review/associated.vue', 1, 2, 0, 0, 0, 0, '超级管理员', '2023-11-15 15:30:08', '超级管理员', '2023-11-29 17:52:22');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4125, '规划&执行', '', 2, 99, 4118, 'plan/:planId/associated-use-cases', 'fa-solid:link', 'PlanAssociatedCase', 'Tracked/plan/associated.vue', 1, 2, 0, 0, 0, 0, '超级管理员', '2023-11-16 11:13:23', '超级管理员', '2023-11-29 17:52:27');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4127, '关联用例', 'review:case:add', 3, 0, 4124, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:23:55', '超级管理员', '2023-11-29 17:23:55');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4128, '解除关联', 'review:case:remove', 3, 1, 4124, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:24:39', '超级管理员', '2023-11-29 17:24:39');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4129, '评审用例', 'review:case:execute', 3, 2, 4124, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:26:03', '超级管理员', '2023-11-29 17:26:03');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4130, '关联用例', 'plan:case:add', 3, 0, 4125, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:26:32', '超级管理员', '2023-11-29 17:26:32');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4131, '解除关联', 'plan:case:remove', 3, 1, 4125, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:26:48', '超级管理员', '2023-11-29 17:26:48');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4132, '执行测试', 'plan:case:execute', 3, 2, 4125, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:27:07', '超级管理员', '2023-11-29 17:27:07');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4133, '新增', 'tracked:plan:add', 3, 0, 4121, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:32:05', '超级管理员', '2023-11-29 17:34:20');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4134, '修改', 'tracked:plan:update', 3, 1, 4121, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:32:25', '超级管理员', '2023-11-29 17:34:26');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4135, '删除', 'tracked:plan:remove', 3, 2, 4121, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:32:45', '超级管理员', '2023-11-29 17:34:32');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4136, '规划&执行', 'tracked:plan:execute', 3, 3, 4121, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:33:57', '超级管理员', '2023-11-29 17:34:39');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4137, '新增', 'tracked:review:add', 3, 0, 4120, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:35:02', '超级管理员', '2023-11-29 17:35:02');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4138, '修改', 'tracked:review:update', 3, 1, 4120, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:35:13', '超级管理员', '2023-11-29 17:35:13');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4139, '删除', 'tracked:review:remove', 3, 2, 4120, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:35:28', '超级管理员', '2023-11-29 17:35:28');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4140, '规划&执行', 'tracked:review:execute', 3, 3, 4120, '', '', '', '', 1, 2, 1, 1, 1, 0, '超级管理员', '2023-11-29 17:35:50', '超级管理员', '2023-11-29 17:35:50');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4141, '归档管理', '', 2, 5, 4110, 'archives', 'fa:file-archive-o', 'ProjectArchive', 'Project/archive/index.vue', 1, 2, 1, 1, 1, 1, '超级管理员', '2023-12-04 11:52:07', '超级管理员', '2023-12-07 14:16:34');
INSERT INTO `sys_menu` (`id`, `name`, `permission`, `menu_type`, `sort`, `parent_id`, `path`, `icon`, `component_name`, `component`, `status`, `page_type`, `visible`, `always_show`, `keep_alive`, `deleted`, `creator`, `create_time`, `updater`, `update_time`) VALUES (4142, '归档详情', '', 2, 99, 4110, 'archive/:id', 'fa:file-archive-o', 'ArchiveDetail', 'Project/archive/detail.vue', 1, 2, 0, 0, 0, 0, '超级管理员', '2023-12-05 16:32:09', '超级管理员', '2023-12-07 14:53:02');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
