server:
  port: 48080

spring:
  application:
    name: web-server
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  lifecycle:
    timeout-per-shutdown-phase: 60s
  # Jackson 配置项
  jackson:
    serialization:
      write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false # 允许序列化无属性的 Bean
  # 数据源配置项
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/migoo?useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456qq
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      #password: sos5561505!

#################### 框架相关配置 ####################

migoo:
  web:
    api-prefix: /${spring.application.name}
    controller-package: com.github.xiaomisum.mstar.controller
    scan-all: true
  captcha:
    timeout: 5m
    width: 160
    height: 60
  xss:
    enable: false
  mybatis:
    mapper-package: com.github.xiaomisum.mstar.dal.mapper
  security:
    token-header: X-Token
    token-secret: 17c553e34228909b1f8cef6d1de0b53d
    token-timeout: 1d
    session-timeout: 30m

# MyBatis Plus 的配置项
mybatis-plus:
  #  在 mybatis-config/mybatis-config.xml 中设置
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印日志
    lazy-loading-enabled: false
  global-config:
    db-config:
      id-type: AUTO # 自增 ID
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/*.xml
  configuration-properties:
    prefix: ""
    wildcardEscapeClause: ""
    limitBefore: ""
    limitAfter: "LIMIT #{maxResults} OFFSET #{firstResult}"
    limitBetween: ""
    limitOuterJoinBetween: ""
    limitBeforeNativeQuery: ""
    orderBy: "order by ${orderByColumns}"
    blobType: "BLOB"
    boolValue: "TRUE"
  #  type-aliases-package: